name: Build emulator with Qt5 GUI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'linux'
        
    - name: Build emulator
      run: |
        cd emulator/
        make
    - name: Build GUI
      run: |
        cd emulator/gui/
        mkdir build
        cd build/
        qmake ..
        make
